-- Insert default admin user
insert into users (
   id,
   name,
   email,
   password_hash,
   role,
   employee_id,
   work_unit,
   phone,
   status,
   is_active,
   is_deleted,
   created_date
) values ( uuid_generate_v4(),
           'Administrator',
           'admin@simpel-ti.com',
           '$2b$12$xbaTNqY7cH12/mzFVWti5e8C7DPdF4sfy5xHrh4UlCCLWmN6VHIPe', -- This should be hashed password for 'admin123'
           'admin',
           'EMP001',
           'teknik-informatika',
           '08123456789',
           'active',
           true,
           false,
           current_timestamp );

-- Insert sample user
insert into users (
   id,
   name,
   email,
   password_hash,
   role,
   student_id,
   study_program,
   faculty,
   whatsapp,
   status,
   is_active,
   is_deleted,
   created_date
) values ( uuid_generate_v4(),
           'User Test',
           'user@simpel-ti.com',
           '$2b$12$CfnQV/ckZpB.wBK0CWjgxOWIPwgvl1ryMQkmSBRn14A.g7J9gEYrS', -- This should be hashed password for 'user123'
           'user',
           '2230RXXX1',
           'teknik-informatika',
           'teknik',
           '08123456790',
           'active',
           true,
           false,
           current_timestamp );

-- Insert sample items
insert into items (
   id,
   code,
   name,
   quantity,
   available,
   borrowed,
   unit,
   category,
   condition,
   is_active,
   is_deleted,
   created_date
) values ( uuid_generate_v4(),
           'LAB-INF-001',
           'Monitor',
           30,
           30,
           0,
           'Unit',
           'Komputer',
           'good',
           true,
           false,
           current_timestamp ),( uuid_generate_v4(),
                                 'LAB-INF-002',
                                 'Motherboard',
                                 25,
                                 20,
                                 5,
                                 'Unit',
                                 'Komputer',
                                 'good',
                                 true,
                                 false,
                                 current_timestamp ),( uuid_generate_v4(),
                                                       'LAB-INF-003',
                                                       'Proyektor',
                                                       2,
                                                       2,
                                                       0,
                                                       'Unit',
                                                       'Elektronik',
                                                       'good',
                                                       true,
                                                       false,
                                                       current_timestamp ),( uuid_generate_v4(),
                                                                             'LAB-INF-004',
                                                                             'Mouse',
                                                                             30,
                                                                             30,
                                                                             0,
                                                                             'Unit',
                                                                             'Komputer',
                                                                             'good',
                                                                             true,
                                                                             false,
                                                                             current_timestamp ),( uuid_generate_v4(),
                                                                                                   'LAB-INF-005',
                                                                                                   'Keyboard',
                                                                                                   30,
                                                                                                   28,
                                                                                                   2,
                                                                                                   'Unit',
                                                                                                   'Komputer',
                                                                                                   'good',
                                                                                                   true,
                                                                                                   false,
                                                                                                   current_timestamp );